/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_badlogicgames_gifski_Gifski */

#ifndef _Included_com_badlogicgames_gifski_Gifski
#define _Included_com_badlogicgames_gifski_Gifski
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_badlogicgames_gifski_Gifski
 * Method:    _newGifski
 * Signature: (IIIZZ)J
 */
JNIEXPORT jlong JNICALL Java_com_badlogicgames_gifski_Gifski__1newGifski
  (JNIEnv *, jclass, jint, jint, jint, jboolean, jboolean);

/*
 * Class:     com_badlogicgames_gifski_Gifski
 * Method:    _drop
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_badlogicgames_gifski_Gifski__1drop
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
