/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_badlogicgames_pngquant_PngQuant */

#ifndef _Included_com_badlogicgames_pngquant_PngQuant
#define _Included_com_badlogicgames_pngquant_PngQuant
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
